# Generated by Django 3.2.4 on 2021-06-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210609_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'филиал', 'verbose_name_plural': 'филиалы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
    ]
