# Generated by Django 3.2.4 on 2021-06-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210609_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='branche',
            new_name='branch',
        ),
    ]
