# Generated by Django 3.2.4 on 2021-06-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210611_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='branch',
            new_name='branche',
        ),
    ]
