# Generated by Django 3.2.4 on 2021-06-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_branch_group_branche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Branch',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='branche',
            new_name='branch',
        ),
    ]
